// ── Planet Data ──────────────────────────────────────────────────────────────
// radius: visual radius in scene units (Earth = 1.0)
// distance: orbital radius from Sun in scene units
// orbitSpeed: revolutions per second at speed=1 (scaled for visual appeal)
// rotationSpeed: self-rotation per second
// color: fallback color
// emissive: for glow
// info: display data

export const SUN_DATA = {
  id: 'soleil',
  name: 'Soleil',
  nameEn: 'Sun',
  aliases: ['sun', 'sol', 'etoile', 'étoile', 'star'],
  icon: '☀️',
  radius: 10.9,       // ~109x Earth
  color: 0xFFF4C2,
  emissive: 0xFFAA00,
  info: {
    type: 'Étoile (Naine Jaune)',
    masse: '1.989 × 10³⁰ kg',
    rayon: '696 340 km',
    temperature: '5 778 K (surface)',
    age: '4.6 milliards d\'années',
    rotation: '25-35 jours',
    luminosite: '3.828 × 10²⁶ W',
    composition: 'Hydrogène 73%, Hélium 25%',
    distance: 'Centre du système',
  },
  description: 'Le Soleil est l\'étoile centrale de notre système solaire. C\'est une naine jaune de type G2V, âgée de 4,6 milliards d\'années. Il représente 99,86% de la masse totale du système solaire et génère son énergie par fusion nucléaire en son cœur, transformant l\'hydrogène en hélium.'
};

export const PLANETS = [
  {
    id: 'mercure',
    name: 'Mercure',
    nameEn: 'Mercury',
    aliases: ['mercury'],
    icon: '⚫',
    radius: 0.383,
    distance: 18,
    orbitSpeed: 0.0241,
    rotationSpeed: 0.017,
    tilt: 0.034,
    color: 0x9E9E9E,
    emissive: 0x444444,
    ringColor: null,
    info: {
      type: 'Planète tellurique',
      rayon: '2 439,7 km',
      masse: '3.301 × 10²³ kg',
      distance: '57,9 millions km',
      revolution: '87,97 jours',
      rotation: '58,65 jours',
      temperature: '-180°C à +430°C',
      lunes: '0',
      gravite: '3,7 m/s²',
    },
    description: 'Mercure est la planète la plus proche du Soleil et la plus petite du système solaire. Elle n\'a presque pas d\'atmosphère, ce qui explique ses températures extrêmes. Sa surface est criblée de cratères, ressemblant à la Lune. Une année sur Mercure ne dure que 88 jours terrestres.'
  },
  {
    id: 'venus',
    name: 'Vénus',
    nameEn: 'Venus',
    aliases: ['venus', 'venux'],
    icon: '🟡',
    radius: 0.949,
    distance: 28,
    orbitSpeed: 0.0162,
    rotationSpeed: -0.018,   // retrograde
    tilt: 177.36,
    color: 0xE8C98A,
    emissive: 0x6B4A00,
    ringColor: null,
    info: {
      type: 'Planète tellurique',
      rayon: '6 051,8 km',
      masse: '4.867 × 10²⁴ kg',
      distance: '108,2 millions km',
      revolution: '224,7 jours',
      rotation: '243 jours (rétrograde)',
      temperature: '462°C (moyenne)',
      lunes: '0',
      gravite: '8,87 m/s²',
    },
    description: 'Vénus est la planète la plus chaude du système solaire malgré n\'étant pas la plus proche du Soleil, en raison d\'un effet de serre extrême. Son atmosphère dense de CO₂ crée une pression 92 fois supérieure à celle de la Terre. Elle tourne dans le sens rétrograde — le Soleil s\'y lève à l\'ouest.'
  },
  {
    id: 'terre',
    name: 'Terre',
    nameEn: 'Earth',
    aliases: ['earth', 'terra', 'world'],
    icon: '🌍',
    radius: 1.0,
    distance: 38,
    orbitSpeed: 0.01,
    rotationSpeed: 0.02,
    tilt: 23.44,
    color: 0x4B9CD3,
    emissive: 0x001133,
    ringColor: null,
    info: {
      type: 'Planète tellurique',
      rayon: '6 371 km',
      masse: '5.972 × 10²⁴ kg',
      distance: '149,6 millions km',
      revolution: '365,25 jours',
      rotation: '23h 56min',
      temperature: '-88°C à +58°C',
      lunes: '1 (Lune)',
      gravite: '9,81 m/s²',
    },
    description: 'La Terre est la troisième planète du système solaire et la seule connue pour abriter la vie. Elle possède un champ magnétique protecteur, une atmosphère riche en azote et oxygène, et 71% de sa surface est couverte d\'eau liquide. Son unique satellite naturel est la Lune.'
  },
  {
    id: 'mars',
    name: 'Mars',
    nameEn: 'Mars',
    aliases: ['mars', 'planete rouge', 'planète rouge', 'red planet'],
    icon: '🔴',
    radius: 0.532,
    distance: 50,
    orbitSpeed: 0.00802,
    rotationSpeed: 0.0194,
    tilt: 25.19,
    color: 0xC1440E,
    emissive: 0x3A0A00,
    ringColor: null,
    info: {
      type: 'Planète tellurique',
      rayon: '3 389,5 km',
      masse: '6.390 × 10²³ kg',
      distance: '227,9 millions km',
      revolution: '686,97 jours',
      rotation: '24h 37min',
      temperature: '-87°C à -5°C',
      lunes: '2 (Phobos, Deimos)',
      gravite: '3,72 m/s²',
    },
    description: 'Mars, la planète rouge, possède le plus grand volcan du système solaire (Olympus Mons, 21 km de haut) et un système de canyons géant (Valles Marineris). Son atmosphère ténue de CO₂ ne protège pas des rayonnements. Des missions robotisées explorent activement sa surface à la recherche de traces de vie passée.'
  },
  {
    id: 'jupiter',
    name: 'Jupiter',
    nameEn: 'Jupiter',
    aliases: ['jupiter'],
    icon: '🟠',
    radius: 11.21,
    distance: 90,
    orbitSpeed: 0.00434,
    rotationSpeed: 0.04,
    tilt: 3.13,
    color: 0xC88B3A,
    emissive: 0x3A2010,
    ringColor: null,
    hasGRS: true,
    info: {
      type: 'Géante gazeuse',
      rayon: '69 911 km',
      masse: '1.898 × 10²⁷ kg',
      distance: '778,5 millions km',
      revolution: '11,86 ans',
      rotation: '9h 56min',
      temperature: '-108°C (nuages)',
      lunes: '95 (dont Io, Europe)',
      gravite: '24,79 m/s²',
    },
    description: 'Jupiter est la plus grande planète du système solaire — elle contient 2,5 fois la masse de toutes les autres planètes réunies. Sa Grande Tache Rouge est un anticyclone qui dure depuis au moins 350 ans. Jupiter joue un rôle crucial comme "bouclier" gravitationnel protégeant la Terre des astéroïdes.'
  },
  {
    id: 'saturne',
    name: 'Saturne',
    nameEn: 'Saturn',
    aliases: ['saturn', 'saturne'],
    icon: '🪐',
    radius: 9.45,
    distance: 135,
    orbitSpeed: 0.00325,
    rotationSpeed: 0.038,
    tilt: 26.73,
    color: 0xE4D58A,
    emissive: 0x3A3010,
    ringColor: 0xC8A96E,
    info: {
      type: 'Géante gazeuse',
      rayon: '58 232 km',
      masse: '5.683 × 10²⁶ kg',
      distance: '1,432 milliards km',
      revolution: '29,46 ans',
      rotation: '10h 33min',
      temperature: '-138°C (nuages)',
      lunes: '146 (dont Titan)',
      gravite: '10,44 m/s²',
    },
    description: 'Saturne est célèbre pour son spectaculaire système d\'anneaux composé de glace et de rochers. C\'est la planète la moins dense du système solaire — elle flotterait sur l\'eau ! Titan, son plus grand satellite, possède une atmosphère dense et des lacs de méthane liquide en surface.'
  },
  {
    id: 'uranus',
    name: 'Uranus',
    nameEn: 'Uranus',
    aliases: ['uranus'],
    icon: '🔵',
    radius: 4.01,
    distance: 185,
    orbitSpeed: 0.00228,
    rotationSpeed: -0.03,   // retrograde
    tilt: 97.77,
    color: 0x7FFFD4,
    emissive: 0x004433,
    ringColor: 0x7FBFBF,
    ringThin: true,
    info: {
      type: 'Géante de glace',
      rayon: '25 362 km',
      masse: '8.681 × 10²⁵ kg',
      distance: '2,867 milliards km',
      revolution: '84,01 ans',
      rotation: '17h 14min (rétrograde)',
      temperature: '-195°C (nuages)',
      lunes: '28 (Miranda, Ariel…)',
      gravite: '8,87 m/s²',
    },
    description: 'Uranus est unique car son axe de rotation est incliné à 98° — elle "roule" sur son orbite ! Cette inclinaison extrême est probablement due à une collision avec un objet de la taille de la Terre il y a des milliards d\'années. C\'est une géante de glace avec une atmosphère riche en méthane qui lui donne sa couleur cyan.'
  },
  {
    id: 'neptune',
    name: 'Neptune',
    nameEn: 'Neptune',
    aliases: ['neptune'],
    icon: '🫧',
    radius: 3.88,
    distance: 230,
    orbitSpeed: 0.00182,
    rotationSpeed: 0.032,
    tilt: 28.32,
    color: 0x4169E1,
    emissive: 0x000A33,
    ringColor: 0x4444AA,
    ringThin: true,
    info: {
      type: 'Géante de glace',
      rayon: '24 622 km',
      masse: '1.024 × 10²⁶ kg',
      distance: '4,495 milliards km',
      revolution: '164,8 ans',
      rotation: '16h 6min',
      temperature: '-201°C (nuages)',
      lunes: '16 (dont Triton)',
      gravite: '11,15 m/s²',
    },
    description: 'Neptune est la planète la plus éloignée du Soleil. Elle possède les vents les plus violents du système solaire, atteignant 2 100 km/h. Triton, son principal satellite, orbite en sens rétrograde et sera déchiré par les forces de marée de Neptune dans environ 3,6 milliards d\'années, formant un nouveau système d\'anneaux.'
  }
];

export const MOON_DATA = {
  id: 'lune',
  name: 'Lune',
  nameEn: 'Moon',
  aliases: ['moon', 'luna', 'lune'],
  icon: '🌕',
  radius: 0.273,
  distanceFromEarth: 3.5,
  orbitSpeed: 0.1,
  rotationSpeed: 0,
  tilt: 6.68,
  color: 0xCCCCCC,
  emissive: 0x999999,
  info: {
    type: 'Satellite naturel',
    rayon: '1 737,4 km',
    masse: '7.342 × 10²² kg',
    distance: '384 400 km (Terre)',
    revolution: '27,32 jours',
    rotation: '27,32 jours (synchrone)',
    temperature: '-173°C à +127°C',
    gravite: '1,62 m/s²',
    age: '4.5 milliards d\'années',
  },
  description: 'La Lune est le seul satellite naturel de la Terre et le cinquième plus grand du système solaire. Elle est en rotation synchrone, montrant toujours la même face à la Terre. Sa gravité est responsable des marées terrestres. L\'Homme a marché sur la Lune pour la première fois le 21 juillet 1969 (Apollo 11).'
};

export const DWARF_PLANETS = [
  {
    id: 'ceres',
    name: 'Cérès',
    nameEn: 'Ceres',
    aliases: ['ceres'],
    icon: '⚪',
    radius: 0.15,
    distance: 64,
    orbitSpeed: 0.0035,
    rotationSpeed: 0.038,
    tilt: 4,
    color: 0xAA9988,
    emissive: 0x221111,
    ringColor: null,
    isDwarf: true,
    info: {
      type: 'Planète naine (Ceinture d\'astéroïdes)',
      rayon: '476 km',
      masse: '9.39 × 10²⁰ kg',
      distance: '414 millions km',
      revolution: '4,6 ans',
      rotation: '9h 4min',
      temperature: '-105°C',
    },
    description: 'Cérès est la plus grande planète naine de la ceinture principale et la seule présente dans le système solaire interne. Découverte en 1801, elle représente un tiers de la masse totale de la ceinture d\'astéroïdes.',
  },
  {
    id: 'pluto',
    name: 'Pluton',
    nameEn: 'Pluto',
    aliases: ['pluto', 'pluton'],
    icon: '🩶',
    radius: 0.35,
    distance: 265,
    orbitSpeed: 0.00065,
    rotationSpeed: -0.004,
    tilt: 122.5,
    color: 0xC8A882,
    emissive: 0x221100,
    ringColor: null,
    isDwarf: true,
    info: {
      type: 'Planète naine (Ceinture de Kuiper)',
      rayon: '1 188 km',
      masse: '1.31 × 10²² kg',
      distance: '5,9 milliards km',
      revolution: '248 ans',
      rotation: '6,4 jours',
      temperature: '-229°C',
      lunes: '5 (Charon, Nix, Hydra…)',
    },
    description: 'Pluton fut considérée comme la neuvième planète de 1930 à 2006. La sonde New Horizons l\'a survolée en 2015, révélant la célèbre région en forme de cœur « Tombaugh Regio ».',
  },
  {
    id: 'eris',
    name: 'Éris',
    nameEn: 'Eris',
    aliases: ['eris'],
    icon: '⬜',
    radius: 0.34,
    distance: 310,
    orbitSpeed: 0.00038,
    rotationSpeed: 0.006,
    tilt: 44,
    color: 0xDDCCBB,
    emissive: 0x111111,
    ringColor: null,
    isDwarf: true,
    info: {
      type: 'Planète naine (Disque épars)',
      rayon: '1 163 km',
      masse: '1.66 × 10²² kg',
      distance: '14,4 milliards km',
      revolution: '559 ans',
      rotation: '~26 heures',
      temperature: '-243°C',
      lunes: '1 (Dysnomia)',
    },
    description: 'Éris est la planète naine la plus massive connue et légèrement plus petite que Pluton en taille. Sa découverte en 2005 a provoqué la redéfinition du terme « planète » et la reclassification de Pluton.',
  },
  {
    id: 'haumea',
    name: 'Hauméa',
    nameEn: 'Haumea',
    aliases: ['haumea', 'haumea'],
    icon: '🥚',
    radius: 0.28,
    distance: 278,
    orbitSpeed: 0.00058,
    rotationSpeed: 0.065,
    tilt: 28,
    color: 0xEEEEDD,
    emissive: 0x111111,
    ringColor: null,
    isDwarf: true,
    info: {
      type: 'Planète naine (Ceinture de Kuiper)',
      rayon: '780 km (axe majeur)',
      masse: '4.01 × 10²¹ kg',
      distance: '6,5 milliards km',
      revolution: '285 ans',
      rotation: '3h 54min',
      temperature: '-241°C',
      lunes: '2 (Hi\'iaka, Namaka)',
    },
    description: 'Hauméa est une planète naine à la forme très allongée (ellipsoïde), due à sa rotation extrêmement rapide. Elle possède un système d\'anneaux, découvert en 2017.',
  },
  {
    id: 'makemake',
    name: 'Makémaké',
    nameEn: 'Makemake',
    aliases: ['makemake', 'makemake'],
    icon: '🟤',
    radius: 0.27,
    distance: 288,
    orbitSpeed: 0.00053,
    rotationSpeed: 0.014,
    tilt: 29,
    color: 0xCC8855,
    emissive: 0x220800,
    ringColor: null,
    isDwarf: true,
    info: {
      type: 'Planète naine (Ceinture de Kuiper)',
      rayon: '715 km',
      masse: '3.1 × 10²¹ kg',
      distance: '6,8 milliards km',
      revolution: '305 ans',
      rotation: '22,5 heures',
      temperature: '-239°C',
      lunes: '1 (MK 2)',
    },
    description: 'Makémaké est la troisième plus grande planète naine du système solaire. Sa surface rouge-brun est due à la présence de tholin (matière organique complexe formée par irradiation).',
  },
];

// Alias lookup map (lowercase key → planet id)
export function buildAliasMap() {
  const map = {};
  const all = [...PLANETS, ...DWARF_PLANETS, MOON_DATA, SUN_DATA];
  for (const body of all) {
    const keys = [
      body.name.toLowerCase(),
      body.nameEn.toLowerCase(),
      body.id,
      ...(body.aliases || [])
    ];
    for (const k of keys) {
      map[k.normalize('NFD').replace(/[\u0300-\u036f]/g, '').toLowerCase()] = body.id;
      map[k.toLowerCase()] = body.id;
    }
  }
  return map;
}
